import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.page}>
      <Head>
        <title>landing-2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.menu}>
        <div className={styles.menu_logo}>
          <Image src="/img/img1.png" alt="Logo" width={352} height={177} />
        </div>
        <div className={styles.btn}>
          <a href="#" rel="nofollow">
            <span>
              DOWNLOAD APP
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                fill="currentColor"
                viewBox="0 0 16 16"
              >
                <path
                  fillRule="evenodd"
                  d="M3.5 10a.5.5 0 0 1-.5-.5v-8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 0 0 1h2A1.5 1.5 0 0 0 14 9.5v-8A1.5 1.5 0 0 0 12.5 0h-9A1.5 1.5 0 0 0 2 1.5v8A1.5 1.5 0 0 0 3.5 11h2a.5.5 0 0 0 0-1h-2z"
                />
                <path
                  fillRule="evenodd"
                  d="M7.646 15.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 14.293V5.5a.5.5 0 0 0-1 0v8.793l-2.146-2.147a.5.5 0 0 0-.708.708l3 3z"
                />
              </svg>
            </span>
          </a>
        </div>
      </div>
      <main className={styles.main}>
        <div className={styles.container}>
          <header className={styles.section_flex}>
            <div className={styles.section_1}>
              <div className={styles.title}>
                Does your child suffer from symptoms of depression and anxiety? 
              </div>
              <div className={styles.subtitle}>
                Childhood anxiety and depression is on the rise all over the
                world.
              </div>
              <div className={styles.subtitle}>
                It’s not easy to provide consistent care for children with A&D.
              </div>
              <div className={styles.subtitle}>
                Mental and emotional therapies are long term daily commitments
                for everyone involved.
              </div>
              <div className={styles.subtitle}>
                Dr. MOOVES A&D is a motion capture app that works as a tool to
                improve children's mental and behavioral health by dance moves.
              </div>
              <div className={styles.btn}>
                <a href="#" rel="nofollow">
                  <span>
                    DOWNLOAD APP
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="16"
                      height="16"
                      fill="currentColor"
                      viewBox="0 0 16 16"
                    >
                      <path
                        fillRule="evenodd"
                        d="M3.5 10a.5.5 0 0 1-.5-.5v-8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 0 0 1h2A1.5 1.5 0 0 0 14 9.5v-8A1.5 1.5 0 0 0 12.5 0h-9A1.5 1.5 0 0 0 2 1.5v8A1.5 1.5 0 0 0 3.5 11h2a.5.5 0 0 0 0-1h-2z"
                      />
                      <path
                        fillRule="evenodd"
                        d="M7.646 15.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 14.293V5.5a.5.5 0 0 0-1 0v8.793l-2.146-2.147a.5.5 0 0 0-.708.708l3 3z"
                      />
                    </svg>
                  </span>
                </a>
              </div>
              <div className={styles.subtitle}>
                Easy and simple! Treat your child from home with a fun dance app
                and <b>get paid!</b>
              </div>
              <div className={styles.title}>
                Download now and start dancing!  
              </div>
            </div>
            <div className={styles.section_2}>
              <div className={styles.video}>
                <div className={styles.logo}>
                  <Image
                    src="/img/img1.png"
                    alt="Logo"
                    width={352}
                    height={177}
                  />
                </div>
                <div>
                  <video width="100%" autoPlay muted>
                    <source src="/img/playfor.mp4" type="video/mp4" />
                    Your browser does not support HTML video.
                  </video>
                </div>
                <div className={styles.btn}>
                  <a href="#" rel="nofollow">
                    <span>
                      DOWNLOAD APP
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="16"
                        height="16"
                        fill="currentColor"
                        viewBox="0 0 16 16"
                      >
                        <path
                          fillRule="evenodd"
                          d="M3.5 10a.5.5 0 0 1-.5-.5v-8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 0 0 1h2A1.5 1.5 0 0 0 14 9.5v-8A1.5 1.5 0 0 0 12.5 0h-9A1.5 1.5 0 0 0 2 1.5v8A1.5 1.5 0 0 0 3.5 11h2a.5.5 0 0 0 0-1h-2z"
                        />
                        <path
                          fillRule="evenodd"
                          d="M7.646 15.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 14.293V5.5a.5.5 0 0 0-1 0v8.793l-2.146-2.147a.5.5 0 0 0-.708.708l3 3z"
                        />
                      </svg>
                    </span>
                  </a>
                </div>
              </div>
            </div>
          </header>
        </div>
      </main>

      <footer className={styles.footer}>
        Playing Forward Copyright 2022. All Rights Reserved.
      </footer>
    </div>
  );
}
